FROM golang:1.25-alpine

WORKDIR /app

COPY ./migrations ./migrations
COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

CMD sh -c "/go/bin/goose -dir ./migrations postgres \"$DATABASE_URL\" up"